[package]
name = "base16ify"
version = "0.1.0"
authors = ["raccoon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
png = "0.16"
regex = "1.5"
yaml-rust = "0.4"
